$
$ 50th Percentile Male Human Body Model (HBM) developed by
$ the University of Michigan Transportation Research Insititute (UMTRI)
$
$ UMTRI HBM M50 V1.2 - Updated 08/23/2022
$ Unit: mm, ms, and kg
$ Contact: Jingwen Hu jwhu@umich.edu
$ Contact: Yang-Shen Lin ynshnlin@umich.edu
$
*KEYWORD
*TITLE
UMTRI_HBM_M50_V1.2
*INCLUDE
UMTRI_HBM_M50_V1.2_Control.k
*INCLUDE
UMTRI_HBM_M50_V1.2_Mesh_Components.k
*INCLUDE
UMTRI_HBM_M50_V1.2_Nodes.k
*END
